### ISSUE TITLE
Performance on allForms graph

### ISSUE THREAD

**Issue by anehx** [projectcaluma/caluma#476] opened 2019-05-31 07:18 UTC
While working on https://github.com/projectcaluma/ember-caluma/issues/296 I noticed that the most expensive request was fetching all needed forms with its questions on `allForms`.

Fetching a filtered set of ~40 forms resulted in a ~50KB request which took ~12000ms to resolve. This is way too slow and does not really make sense to me since we don't do any nesting in [said query](https://github.com/projectcaluma/ember-caluma/blob/545379e830767ec1dc5a29a4f0c539e2fbc1b5e7/addon/gql/queries/get-navigation-forms.graphql).

**Comment by winged** [comment] 2019-06-03 08:04
Were you able to verify that the work from #473 (especially 4c001ac13b86b6c073d01880868091d741a9e2f0) help with this?

**Comment by anehx** [comment] 2019-06-03 14:50
No, it even with that filter, the request still took that long to resolve..

**Comment by sliverc** [comment] 2019-07-10 15:22
PRs #569 #568 #563 should improve the situation but the main performance hit - the query explosion on FormQuestion -> questions -> options is not solved with it.

The problem is that `prefetch_related` doesn't really work as each connection can be filtered (filters and visibility layer). This would technically work with [Prefetch](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.Prefetch) but for this all queryset connections would need to be pre-calucated according to the analyzed query.

There is a tool [graphene-django-optimizer](https://github.com/tfoxy/graphene-django-optimizer) trying to do this but it doens't work with Django Filter or `get_queryset` overwrite as we use it for visibility classes. Also as I understand it it doesn't work with nested connections which are our main problem.

See also https://github.com/tfoxy/graphene-django-optimizer/issues/17 or https://github.com/graphql-python/graphene-django/issues/57 for more details.

I suggest we look at the performance gain with the suggested fixes and see whether there is still a need to dig into this further.

**Comment by sliverc** [comment] 2019-07-11 09:43
Thinking about this again main issue is the ManyToMany fields which lead to query explosions.
This could be replaced with ArrayField - loosing constraints but opening the door to use [data loaders](https://docs.graphene-python.org/en/latest/execution/dataloader/).

I will give it a try and see whether there are any drawbacks beside a major code change... :wink:

**Comment by sliverc** [comment] 2019-07-12 10:07
see #572 but not so convinced the drawback is really worth the performance gain. Best to be widely discussed... :wink:

**Comment by sliverc** [comment] 2019-07-23 13:48
instead of #572 implemented #596

With all the fixes done do you think we can close this issue?

**Comment by czosel** [comment] 2019-07-23 16:01
I’d say for the moment we can consider the performance issue fixed! Thanks for the awesome work! 💯🎉

**Closed by czosel** 2019-07-23 16:01 UTC
Labels: enhancement, prio: high
